shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3

packages:
  - .
  - 'examples/*'

catalog:
  '@antfu/eslint-config': ^7.4.2
  '@types/node': ^24.13.3
  '@vitest/runner': 4.1.10
  eslint: ^10.0.0
  execa: ^10.0.1
  typescript: ^5.9.3
  typescript-to-gdscript: github:LemonNekoGH/typescript-to-gdscript#78058f173ef8d38949532037998b3c86407eec7d
  vitest: 4.1.10

allowBuilds:
  tree-sitter: true
  tree-sitter-gdscript: true
  tree-sitter-godot-resource: true
